### ISSUE TITLE
Add range mapping filters

### ISSUE THREAD

**Issue by Doralitze** [Mission-DMX/realtime-fish#49]
We need filters to automatically map a 16 bit number (0 to 65535) to an eight bit one (0 to 255).
Furthermore we need a filter to automatically map a float (0 to 1) to 8bit or 16bit with selectable lower and upper bounds.

**Comment by LRahlff** [comment]
does the filter 16bit_to_dual_byte realize the first part?
do you need the second part that often? you can achieve this by using a MAC filter and a conversion filter?

**Comment by Doralitze** [comment]
> does the filter 16bit_to_dual_byte realize the first part?
No, it does not. The `16bit_to_dual_byte` filter splits the data into two separate numbers. This is used to encode 16 bit values using two channels in DMX. The filter I spoke about on the other hand, map the value space. This means:
* 0->0
* 64->16384
* 128->32768
* 192->49152
* 255->65535

And all other values in between. Basically $out=\frac{in}{256}*2^{16}$

> do you need the second part that often? you can achieve this by using a MAC filter and a conversion filter?

Actually, I think yes. But it is also just a convince tool for $out=in*(upper-lower)+lower$. But as upper and lower are constant parameters, this would make designing effects definitely faster.

**Comment by LRahlff** [comment]
Question to the second filter:
Do you want to set the lower and upper bound on the output side? so the input-range is between 0 and 1 and should be mapped to a custom range?
or do you want to set the range for the input float and calculate the value between 0 and 255 (65535).

**Comment by Doralitze** [comment]
> Question to the second filter: Do you want to set the lower and upper bound on the output side? so the input-range is between 0 and 1 and should be mapped to a custom range? or do you want to set the range for the input float and calculate the value between 0 and 255 (65535).

Well, I'd like to have a filter that can map from an (M,N) range to a (K,L) one. So it should be able to do both. But I would set the ranges using the filter configuration.
